import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { FaBeer } from 'react-icons/fa'

import Layout from '../components/Layout'

export default function Home() {
  return (
    <div className='container'>
      <Head>
        <title>ZVIZ</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='stylesheet' href='' />
        <link rel='apple-touch-icon' href='./logo2.webp' />
        <link rel='shortcut icon' type='image/png' href='./logo2.png' />
        <link rel='icon' href='./logo2.png' type='image/png' />
      </Head>

      <Layout>
        <h1>THIS IS HOME PAGE</h1>

        <p>
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Obcaecati
          aut eos eaque ipsa eum reiciendis corrupti corporis dolorem voluptas
          possimus aliquid veniam magnam tenetur veritatis beatae, nam, nihil
          aperiam illum. Atque quia error voluptate voluptatem vel laboriosam
          necessitatibus voluptas omnis. Perferendis eaque maiores cupiditate
          similique atque delectus deleniti, unde autem officiis, facilis libero
          asperiores, dolorum ad voluptate. Neque sit cumque nobis voluptatum
          ducimus necessitatibus quod distinctio nostrum id voluptatem sunt
          debitis repudiandae soluta, deserunt vitae porro natus voluptate,
          tempora est asperiores officia non vel possimus? Quia obcaecati
          cupiditate delectus deleniti, quae eius nesciunt, repudiandae cum
          voluptatum consectetur dicta sapiente omnis?
        </p>
        <h3>
          <FaBeer />
        </h3>
        <p>
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Obcaecati
          aut eos eaque ipsa eum reiciendis corrupti corporis dolorem voluptas
          possimus aliquid veniam magnam tenetur veritatis beatae, nam, nihil
          aperiam illum. Atque quia error voluptate voluptatem vel laboriosam
          necessitatibus voluptas omnis. Perferendis eaque maiores cupiditate
          similique atque delectus deleniti, unde autem officiis, facilis libero
          asperiores, dolorum ad voluptate. Neque sit cumque nobis voluptatum
          ducimus necessitatibus quod distinctio nostrum id voluptatem sunt
          debitis repudiandae soluta, deserunt vitae porro natus voluptate,
          tempora est asperiores officia non vel possimus? Quia obcaecati
          cupiditate delectus deleniti, quae eius nesciunt, repudiandae cum
          voluptatum consectetur dicta sapiente omnis?
        </p>

        <p>
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Obcaecati
          aut eos eaque ipsa eum reiciendis corrupti corporis dolorem voluptas
          possimus aliquid veniam magnam tenetur veritatis beatae, nam, nihil
          aperiam illum. Atque quia error voluptate voluptatem vel laboriosam
          necessitatibus voluptas omnis. Perferendis eaque maiores cupiditate
          similique atque delectus deleniti, unde autem officiis, facilis libero
          asperiores, dolorum ad voluptate. Neque sit cumque nobis voluptatum
          ducimus necessitatibus quod distinctio nostrum id voluptatem sunt
          debitis repudiandae soluta, deserunt vitae porro natus voluptate,
          tempora est asperiores officia non vel possimus? Quia obcaecati
          cupiditate delectus deleniti, quae eius nesciunt, repudiandae cum
          voluptatum consectetur dicta sapiente omnis?
        </p>
      </Layout>
    </div>
  )
}
