import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'

import Layout from '../components/Layout'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>ZVIZ</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='stylesheet' href='' />
        <link rel='apple-touch-icon' href='./logo2.webp' />
        <link rel='shortcut icon' type='image/png' href='./logo2.png' />
        <link rel='icon' href='./logo2.png' type='image/png' />
      </Head>

      <Layout>
        <div className='container-fluid main-cont mt-5'>
          <div className='row align-items-center my-5'>
            <div className='col-6'>
              <div className='text-center'>
                <img
                  src='/hdd3.png'
                  alt='Hard disk drive mechanism'
                  id='imgz'
                  className='img-fluid'
                  width='500px'
                />
              </div>
            </div>
            <div className='col align-self-center pushdown'>
              <h1 className='mt-5'>Welcome to</h1>
              <h2 id='compname' className='display-4 my-3'>
                <span>CHIA</span> <span>BUY</span> <span>PLOTS</span>
              </h2>
              <p className='lead my-3'>Do you want to farm on Chia Network ?</p>
              <p className='lead my-3'>Ready to jump-start with 100+ plots ?</p>
              <p className='lead my-3'>
                Are you in a need to add more plots to your existing chia farm ?
              </p>
              <div className='my-5'>
                <a
                  href='#pitch'
                  id='lan-btn'
                  className='btn btn-success btn-lg'
                >
                  Learn more
                </a>
              </div>
            </div>
          </div>
        </div>
        <div className='jumbotron' alt='green shamrock, credits Brazil_Topno'>
          <div className='text-center'>
            <p className='lead py-5'>
              Let your farm bloom and get ready to collect rewards. Speed up
              your harvest time and enjoy the flavor of freshly picked XCH
              leaves.
            </p>
          </div>
        </div>

        <section id='pitch'>
          <div className='container my-5'>
            <p className='lead'>
              With the computing power that we have, we can generate 110 plots
              per day. Our current stock allows us to set for sale extra plots
              that we have in circulation. All plots that are available for sale
              are k-32 size.
            </p>
            <div className='container my-3'>
              <div className='row justify-content-md-center'>
                <div className={styles.cardz}>
                  <Image
                    width={500}
                    height={300}
                    src='/yachi.webp'
                    alt='Chia network logo, green chia leaf on dark-green background'
                  />
                  <div className=''>
                    <div className='card-body'>
                      <h5 className='card-title'>PLOTS INFO</h5>
                      <h2 className='card-text'>K-32</h2>
                    </div>
                    <ul className='list-group list-group-flush'>
                      <li className='list-group-item'>Size: 101.3GB</li>
                      <li className='list-group-item'>Exp. date: 2026</li>
                      <li className='list-group-item'>Stock: 350 plots</li>
                      <li className='list-group-item' id='money'>
                        Price: <strong> €3</strong> or <strong>$3.66</strong>
                      </li>
                    </ul>
                    <div className='card-body'>
                      <a
                        href='/contact'
                        className='btn  btn-success'
                        title='Get a quote'
                      >
                        Get A Quote
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <p className='lead'>
              We are purposely not allowing direct purchase on the page because
              we want to make sure that our customers are well informed and
              familiar with how chia-network works and the technology behind it.
            </p>
            <p className='text-center'>
              The only reason why we are listing plots for sale is due to our
              shortage of storage space
            </p>
          </div>
        </section>
        <br />
        <br />
        <br />
        <br />
        <br />

        <div className='jumbotron' alt='green shamrock, credits Brazil_Topno'>
          <div className='text-center'>
            <p className='lead py-5'>
              Triple your chances to be awarded with XCH coins. Get your new
              plots today!
            </p>
          </div>
        </div>

        <br />
        <br />
        <br />
        <br />
        <br />

        <div className='container-fluid'>
          <div className='row'>
            <div className='col-lg-6 col-md-12 col-sm-12'>
              <div className='container'>
                <div className='text-center my-3'>
                  <Image
                    width={600}
                    height={400}
                    src='/rocket3.webp'
                    alt='Space  shuttle lauch during daytime'
                    className='img-fluid'
                  />
                </div>
              </div>
            </div>

            <div className='col-lg-6 col-md-12 col-sm-12'>
              <div className='container' id='article1'>
                <div className='text-center'>
                  <h3 className='mt-4'>GET READY TO START</h3>

                  <p className='lead mt-5'>
                    The way to get started and be ahead of the competition with
                    plot count is a huge advantage. Save valuable plotting time
                    and start farming.
                    <br />
                    <br />
                    With these tactics, you are saving tons of time and
                    increasing your odds to farm rewards.
                    <br />
                    <br />
                    Total Netspace is growing out of proportion due to Chinese
                    farmers getting involved. At the time of this writing,
                    Netspace is over 4.2 <strong>EiB</strong> when calculated to
                    terabytes we are getting the sum of 4.200.000{' '}
                    <strong>TiB</strong>.
                  </p>
                </div>
              </div>
            </div>
          </div>
          <br />
          <br />
          <br />
          <br />
          <br />
          <div className='container'>
            <div className='my-5' id='article2'>
              <div className='text-center'>
                <h3>About CHIA</h3>
                <br />
                <p className='lead my-3'>
                  CHIA_NETWORK is a serious contender for the top 20
                  cryptocurrencies of the future.
                  <br />
                  <br />
                  Founded by Bram Cohen inventor of BitTorrent, one of the best
                  network engineers of our age. Stacked and armed with an
                  experienced team behind him they have serious intentions to
                  become the most-spread cryptocurrencies worldwide and replace
                  the spot Bitcoin. Chia Network is dedicated to building a
                  better blockchain and smart transaction and provides a
                  decentralized platform that is more efficient, and more
                  secure.
                  <br />
                  <br />
                  Its cost efficiency, power usage, and proof of space and time
                  are getting more attention from big investors and
                  crypto-enthusiasts. Chia network green money for the future.
                </p>
              </div>
            </div>
          </div>
        </div>
        <div className='container'>
          <div className='text-center my-5'>
            <a
              title='Chia Network official webpage'
              alt='Chia Network, official website'
              className='green-link'
              href='https://www.chia.net'
              target='_blank'
            >
              Visit Chia's Official webpage
            </a>
          </div>
        </div>
      </Layout>
    </>
  )
}
